force_cast: warning # Eventually this should be removed and reverted back to an error.

force_try:
  severity: warning # explicitly

analyzer_rules: # rules run by `swiftlint analyze`
  - capture_variable
  - explicit_self
  - typesafe_array_init
  - unused_declaration
  - unused_import

opt_in_rules: # some rules are only opt-in
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  # - anyobject_protocol # Verified disabled
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - blanket_disable_command
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation # Verified
  - closure_parameter_position
  - closure_spacing # Verified
  - collection_alignment # Verified
  - colon
  - comma
  - comma_inheritance
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - conditional_returns_on_newline
  - contains_over_filter_count # Verified
  - contains_over_filter_is_empty # Verified
  - contains_over_first_not_nil # Verified
  - contains_over_range_nil_comparison # Verified
  - control_statement
  - convenience_type # Verified
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - direct_return
  - discarded_notification_center_observer # Verified
  - discouraged_assert
  - discouraged_direct_init # Verified
  - discouraged_none_name
  - discouraged_object_literal # Verified
  - discouraged_optional_boolean # Verified
  - discouraged_optional_collection
  - duplicate_conditions
  - duplicate_enum_cases # Verified
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal # Verified
  - empty_count # Verified
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  # - explicit_acl # Verified disabled
  - explicit_enum_raw_value
  - explicit_init # Verified
  # - explicit_top_level_acl # Verified disabled
  - explicit_type_interface
  # - extension_access_modifier # Verified disabled
  - fallthrough
  - fatal_error_message
  - file_header
  - file_length
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where # Verified
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping # Verified
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - ibinspectable_in_extension
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - inclusive_language
  # - magic_numbers # Verified disabled
  - indentation_width
  # - inert_defer # Verified disables
  - invalid_swiftlint_command
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - mark
  - missing_docs
  - modifier_order
  - multiline_arguments
  # - multiline_arguments_brackets # Verified disabled
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator # Verified
  - no_extension_access_modifier # Verified
  - no_fallthrough_only
  - no_grouping_extension
  - no_space_in_method_call
  - non_overridable_class_declaration
  - notification_center_detachment
  - ns_number_init_as_function_reference
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace # Verified
  - operator_whitespace
  - optional_enum_case_matching
  - orphaned_doc_comment
  - overridden_super_call # Verified
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  # - prefer_nimble # Verified disabled
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_subject
  - private_swiftui_state
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call # Verified
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_self_in_closure
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  # - required_deinit # Verified disabled - too noisy
  - required_enum_case
  - return_arrow_whitespace
  - return_value_from_void_function
  - self_binding
  - self_in_property_initialization
  - shorthand_operator
  - shorthand_optional_binding
  - single_test_class
  - sorted_enum_cases
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - superfluous_disable_command
  - superfluous_else
  - switch_case_alignment
  - switch_case_on_newline # Verified
  - syntactic_sugar
  - test_case_accessibility
  - todo
  - toggle_bool
  - trailing_closure
  # - trailing_comma # Verified disabled
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_contents_order
  - type_name
  - unavailable_condition
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_break_in_switch
  - unneeded_override
  - unneeded_parentheses_in_closure_argument
  - unneeded_synthesized_initializer
  - unowned_variable_capture
  - untyped_error_in_catch
  # - unused_capture_list # Verified disabled
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call # Verified
  - vertical_whitespace
  - vertical_whitespace_between_cases # Verified
  - vertical_whitespace_closing_braces # Verified
  - vertical_whitespace_opening_braces
  - void_function_in_ternary
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - xctfail_message
  - yoda_condition

# Elevate warnings to errors
class_delegate_protocol:
  severity: error
closing_brace:
  severity: error
closure_spacing:
  severity: error
collection_alignment:
  severity: error
compiler_protocol_init:
  severity: error
colon:
  severity: error
comma:
  severity: error
contains_over_filter_count:
  severity: error
contains_over_filter_is_empty:
  severity: error
contains_over_first_not_nil:
  severity: error
contains_over_range_nil_comparison:
  severity: error
convenience_type:
  severity: error
control_statement:
  severity: error
discarded_notification_center_observer:
  severity: error
discouraged_direct_init:
  severity: error
discouraged_object_literal:
  severity: error
duplicate_imports:
  severity: error
duplicate_enum_cases:
  severity: error
indentation_width:
  indentation_width: 2
  include_compiler_directives: false
empty_collection_literal:
  severity: error
empty_count:
  severity: error
operator_usage_whitespace:
  severity: error
overridden_super_call:
  severity: error
mark: error
missing_docs:
  severity: error
nesting:
  type_level: 2
statement_position:
  severity: error
superfluous_disable_command: error
trailing_whitespace:
  severity: error
trailing_newline:
  severity: error
vertical_whitespace:
  severity: error
vertical_parameter_alignment_on_call:
  severity: error
vertical_whitespace_between_cases:
  severity: error
vertical_whitespace_closing_braces:
  severity: error
orphaned_doc_comment:
  severity: error

disabled_rules:
  - anyobject_protocol
  - extension_access_modifier
  - opening_brace
  - switch_case_alignment
  - todo
  - trailing_comma
  - unused_capture_list

identifier_name:
  min_length:
    error: 2
  excluded:
    - id
    - to
    - gb
    - uk
    - us
    - es
    - ok
    - vc
    - sR
    - sG
    - sB
    - eR
    - eG
    - eB
    - at
    - e
    - i
    - h # HSLuv hue
    - s # HSLuv saturation
    - l # HSLuv lightness
    - u # HSLuv variable
    - v # HSLuv variable
    - r # HSLuv red
    - g # HSLuv green
    - b # HSLuv blue
    - a # HSLuv alpha
    - c # HSLuv variable
    - x # HSLuv variable
    - y # HSLuv variable
    - z # HSLuv variable
    - m # HSLuv Constant

file_length:
  warning: 800
  error: 1000

large_tuple:
  warning: 4
  error: 5

line_length:
  warning: 100
  error: 100

# they can set both implicitly with an array
type_body_length:
  - 600 # warning
  - 600 # error

excluded:
  - "**/.build"
  - "**/checkouts"
  - "**/Package.swift"
  - Pods
  - Carthage
  - SwiftPlaygrounds
